server:
  port: 8081

spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: postgres
  flyway:
    schemas: products
  jpa:
    properties:
      hibernate:
        default_schema: products